
services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    env_file:
       - /workspaces/10p2/frontend/.env.local
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - /workspaces/10p2/frontend/db/schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  postgres_data: