
services:
  frontend:
    depends_on:
      - dynamodb-local
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.local
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DYNAMODB_ENDPOINT=http://dynamodb-local:8000

  dynamodb-local:
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    command: >
      dynamodb create-table
      --endpoint-url http://dynamodb-local:8000
      --table-name FocusAppData
      --attribute-definitions
      AttributeName=PK,AttributeType=S
      AttributeName=SK,AttributeType=S
      --key-schema
      AttributeName=PK,KeyType=HASH
      AttributeName=SK,KeyType=RANGE
      --billing-mode PAY_PER_REQUEST
      

    
  