apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: focus-app-dev

commonLabels:
  environment: development

patches:
  - path: patches/frontend-replicas.yaml
