apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
    component: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        component: ui
    spec:
      containers:
      - name: frontend
        image: ${DOCKER_REGISTRY}/frontend:latest
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: DYNAMODB_ENDPOINT
          value: "http://dynamodb-local:8000"
        - name: DYNAMODB_REGION
          value: "us-east-1"
        - name: DYNAMODB_ACCESS_KEY_ID
          value: "local"
        - name: DYNAMODB_SECRET_ACCESS_KEY
          value: "local"
        - name: DYNAMODB_TABLE_NAME
          value: "FocusAppData"
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "100m"
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 20
          periodSeconds: 15
