apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
    component: ui
spec:
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 3000
      name: http
  type: ClusterIP
