apiVersion: v1
kind: Service
metadata:
  name: dynamodb-local
  labels:
    app: dynamodb-local
    component: database
spec:
  selector:
    app: dynamodb-local
  ports:
    - port: 8000
      targetPort: 8000
      name: dynamodb
  type: ClusterIP
