services:
  mongodb:
    image: "mongo:latest"
    container_name: mongodb
    volumes:
      - ./data:/data/db
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=root
    #   - MONGO_INITDB_ROOT_PASSWORD=example
    ports:
      - "27017:27017"
